language: c
sudo: false
install:
  - curl -L https://github.com/raphink/travis-texlive/releases/download/2015-05-13_01/texlive.tar.xz | tar xJC ~
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  - wget https://bitbucket.org/georgd/eb-garamond/downloads/EBGaramond-0.016.zip
  - unzip EBGaramond-0.016.zip
  - cp EBGaramond-0.016/otf/* fonts/
matrix:
  include:
    - env: BUILD=pdf DEPLOY=true
      script: make charismanie.pdf charismanie_interior.pdf LATEX_INTERACTION="nonstopmode -halt-on-error"
    - env: BUILD=epub
      script: make charismanie.epub
  allow_failures:
    - env: BUILD=epub
# https://github.com/travis-ci/travis-ci/issues/5145
before_deploy:
  - gem install mime-types -v 2.6.2
deploy:
  provider: releases
  api_key:
    secure: FWC4Dt115sXLgyN/wEFdNOASIoCGZCxIzx/O1ESIZ4QCE2wxUUn1goOpLNMSFJ8MPlWgwPZLfGCRHG/LvvnQ/2n1rOAfG/ri7L9Qw2JCVBi2KhJ3K6QDGla0KsAuAaKQZv2TKRcGSx/EO3UcL+tn/DxcIa9GZ8n4lbuUuJFWcOA=
  file:
    - charismanie.pdf
    - charismanie_interior.pdf
  skip_cleanup: true
  on:
    tags: true
