language: c
sudo: false
install:
  - curl -L https://raw.githubusercontent.com/krlmlr/texlive-squashfs/master/out/texlive.tar.xz | tar xJC ~
  - PATH=$HOME/texlive/bin/x86_64-linux:$PATH
  # EB Garamond
  - wget https://bitbucket.org/georgd/eb-garamond/downloads/EBGaramond-0.016.zip
  - unzip EBGaramond-0.016.zip
  - cp EBGaramond-0.016/otf/* fonts/
matrix:
  include:
    - env: DEPLOY=true
      script: make charismanie.pdf LATEX_INTERACTION="nonstopmode -halt-on-error"
    - script: make charismanie.epub
deploy:
  provider: releases
  api_key: "pFrDpJ9AEUu036bK62SfJe0bH51M3oGGLieCl5FTumXAaOJ0ozQ4fVzwLhYTGkihuOWFwzaoY2e145RiNa5Yv6bcQSv/pb9Xnwcl9bUevYJml7Vvz43Q2Afj0NZGqPbe33cquidkyMrTMTtmaEhOOhWcs8Lvulh4yP0MZpxQdT8="
  file: charismanie.pdf
  skip_cleanup: true
  on:
    tags: true
    env: DEPLOY=true
